# Generated by Django 6.0.4 on 2026-04-08 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Imovel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descricao', models.TextField()),
                ('tipo_imovel', models.CharField(choices=[('Apartamento', 'Apartamento'), ('Casa', 'Casa'), ('Terreno', 'Terreno'), ('Sala Comercial', 'Sala Comercial')], max_length=50)),
                ('tipo_finalidade', models.CharField(max_length=50)),
                ('finalidade', models.CharField(max_length=50)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_condominio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iptu', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('area_util', models.IntegerField()),
                ('quartos', models.IntegerField(default=0)),
                ('suites', models.IntegerField(default=0)),
                ('banheiros', models.IntegerField(default=0)),
                ('vagas', models.IntegerField(default=0)),
                ('bairro', models.CharField(max_length=100)),
                ('endereco', models.CharField(max_length=255)),
                ('cidade', models.CharField(default='Belém', max_length=100)),
                ('comodidades_condominio', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
