# Generated by Django 6.0.4 on 2026-04-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0002_imagemimovel'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
    ]
