# Generated by Django 6.0.4 on 2026-04-09 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0003_imovel_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telefone', models.CharField(max_length=20)),
                ('mensagem', models.TextField()),
                ('status', models.CharField(choices=[('novo', 'Novo Contato'), ('atendimento', 'Em Atendimento'), ('fechado', 'Negócio Fechado'), ('perdido', 'Perdido/Desistiu')], default='novo', max_length=20)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('imovel_interesse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='imoveis.imovel')),
            ],
        ),
    ]
