# Generated by Django 6.0.4 on 2026-04-13 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0004_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='cep',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='imovel',
            name='complemento',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='imovel',
            name='numero',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
