# Generated by Django 6.0.4 on 2026-04-13 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0005_imovel_cep_imovel_complemento_imovel_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='meio_contato',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='melhor_horario',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
