# Generated by Django 6.0.4 on 2026-04-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0006_lead_meio_contato_lead_melhor_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='imovel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='imovel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True),
        ),
    ]
