# Generated by Django 6.0.4 on 2026-04-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imoveis', '0007_imovel_latitude_imovel_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imovel',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='imovel',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
    ]
